version: "2"

volumes:
  db-data:
    external: false
  # esdata1:
  #   driver: local
  # esdata2:
  #   driver: local

services:
  db:
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    image: postgres:9.5-alpine
    volumes:
      - db-data:/usr/local/psql/data
  
  fluentd:
    image: fluent/fluentd:latest
    volumes:
      - "/data/:/fluentd/log"
    ports:
      - 24224:24224
      - 24224:24224/udp
    environment:
      # - FLUENTD_CONF=fluent.docker.conf
      - FLUENTD_OPT=-v

  app:
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - db
  
  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000/tcp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge