version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    image: postgres:9.5-alpine
    volumes:
      - db-data:/usr/local/psql/data
  
  mongo:
    image: "mongo:3"
  
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  
  graylog:
    image: graylog2/server:2.2.1-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "5555:5555"
      - "12201:12201"
  
  app:
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - db

